In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('../data/raw/global_pharmacy_sales_2020_2025_daily_dataset.csv')

In [3]:
df.head()

,date,year,month,day,region,country,category,medicine,age_group,units_sold,unit_price,stock_level,expiry_days_remaining,covid_flag
0,2025-10-12,2025,10,12,Middle East,UAE,Chronic,Amlodipine,0-12,328,45.38,4774,466,0
1,2020-09-15,2020,9,15,South Asia,India,Chronic,Amlodipine,26-45,371,75.49,4584,181,1
2,2020-02-26,2020,2,26,Middle East,UAE,Vitamin,Vitamin C,0-12,948,22.51,3934,556,1
3,2025-11-09,2025,11,9,South Asia,Sri Lanka,Chronic,Amlodipine,0-12,275,63.29,4544,330,0
4,2022-04-04,2022,4,4,South America,Argentina,Chronic,Amlodipine,26-45,563,44.28,4284,590,0

In [4]:
df.shape

(177990, 14)

In [5]:
df.columns

Index(['date', 'year', 'month', 'day', 'region', 'country', 'category',
       'medicine', 'age_group', 'units_sold', 'unit_price', 'stock_level',
       'expiry_days_remaining', 'covid_flag'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177990 entries, 0 to 177989
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   date                   177990 non-null  object
 1   year                   177990 non-null  int64
 2   month                  177990 non-null  int64
 3   day                    177990 non-null  int64
 4   region                 177990 non-null  object
 5   country                177990 non-null  object
 6   category               177990 non-null  object
 7   medicine               177990 non-null  object
 8   age_group              177990 non-null  object
 9   units_sold             177990 non-null  int64
 10  unit_price             177990 non-null  float64
 11  stock_level            177990 non-null  int64
 12  expiry_days_remaining  177990 non-null  int64
 13  covid_flag             177990 non-null  int64
dtypes: float64(1), int64(7), object(6)
memory usage: 19.0+ MB

In [7]:
df.describe()

,year,month,day,units_sold,unit_price,stock_level,expiry_days_remaining,covid_flag
count,177990.000000,177990.000000,177990.000000,177990.000000,177990.000000,177990.000000,177990.000000,177990.000000
mean,2022.499702,6.521754,15.730457,447.913849,52.554729,4552.991780,374.038109,0.333519
std,1.708113,3.448703,8.801170,338.924528,27.421909,346.608511,199.759193,0.471471
min,2020.000000,1.000000,1.000000,31.000000,5.000000,0.000000,30.000000,0.000000
25%,2021.000000,4.000000,8.000000,284.000000,28.770000,4443.000000,200.000000,0.000000
50%,2023.000000,7.000000,16.000000,387.000000,52.600000,4598.000000,374.000000,0.000000
75%,2024.000000,10.000000,23.000000,529.000000,76.310000,4735.000000,547.000000,1.000000
max,2025.000000,12.000000,31.000000,8704.000000,100.000000,5124.000000,720.000000,1.000000

In [8]:
df.isnull().sum()

date                     0
year                     0
month                    0
day                      0
region                   0
country                  0
category                 0
medicine                 0
age_group                0
units_sold               0
unit_price               0
stock_level              0
expiry_days_remaining    0
covid_flag               0
dtype: int64

In [10]:
df.duplicated().sum()

2630

In [16]:
df = df.drop_duplicates()

In [17]:
df.duplicated().sum()

0

In [18]:
df['date'] = pd.to_datetime(df['date'])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175360 entries, 0 to 177989
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   date                   175360 non-null  datetime64[ns]
 1   year                   175360 non-null  int64
 2   month                  175360 non-null  int64
 3   day                    175360 non-null  int64
 4   region                 175360 non-null  object
 5   country                175360 non-null  object
 6   category               175360 non-null  object
 7   medicine               175360 non-null  object
 8   age_group              175360 non-null  object
 9   units_sold             175360 non-null  int64
 10  unit_price             175360 non-null  float64
 11  stock_level            175360 non-null  int64
 12  expiry_days_remaining  175360 non-null  int64
 13  covid_flag             175360 non-null  int64
 14  revenue                175360 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(7), object(5)
memory usage: 21.4+ MB

In [20]:
df['revenue'] = df['units_sold'] * df['unit_price']

In [21]:
df[['units_sold', 'unit_price', 'revenue']].head()

   units_sold  unit_price   revenue
0         328       45.38  14884.64
1         371       75.49  28006.79
2         948       22.51  21339.48
3         275       63.29  17404.75
4         563       44.28  24929.64

In [22]:
df.to_csv('../data/processed/pharma_sales_cleaned.csv', index=False)